---
- name: install apache
  hosts: all
  become: true
  tasks:
  - name: install apache2 on s1
    apt: name=apache2 update_cache=yes state=latest

  - name: start apache2 service
    service: name=apache2 state=started
